### ISSUE TITLE
Did you get the find handlebar helpers to work?

### ISSUE THREAD

**Issue by jeroentbt** [zeroasterisk/Presenteract#1]
Hey,

got here through http://stackoverflow.com/a/16784394/1929897

Just wondering if you got those find and findOne helpers going. I don't seem to find any examples in your code. Can't get it to work myself either :/

**Comment by zeroasterisk** [comment]
Sorry - i have not tried yet, I've been making helpers as needed (but I should really look into these helpers sometime)...  looking at them again, it looks like it wants an object in json formatted string for the params...

**Comment by jeroentbt** [comment]
but how would you call it in your HTML?
Even when I hardcode the query etc, and return what is supposed to be a cursor to a collection, I don't seem to be able to `{{#each}}` over them.
Any pointers there?

But that would only solve half my problem :) The query itself would have to be constructed by another handlebars call. I'm probably complicating things... :D

**Comment by zeroasterisk** [comment]
well, each is used ALL the time in Meteor templates... for example:
https://github.com/zeroasterisk/Presenteract/blob/master/client/views/deckEdit.html#L14-16

You certainly don't have to pass in a child template within each, but you can (as I did ^)

basically if you have:

```
Template.whatever.helpers({  
  myitems: function() { 
    return [{id:1, name:'alan'}, {id:2, name:'bob'}]; 
  } 
});
```

you should be able to:

```
{{#each myitems}} id = {{id}} &amp; name = {{name}} {{/each}}
```

you can also use `each` for any result set from a collection
